rule genelist_summary:
    input:
        homology=expand(
            "results/homology/blast-pf15-intergenic-regions-celegans-transcripts-{min_length}-bp-{min_pct_id}-pctid-genes.unique-genes.txt",
            min_length=config["params"]["blast"]["min_length"],
            min_pct_id=config["params"]["blast"]["min_pct_id"],
        ),
        homology_gene_expression=expand(
            "results/homology/blast-pf15-intergenic-regions-celegans-transcripts-{min_length}-bp-{min_pct_id}-pctid-genes-expressed-{{expression}}.unique-genes.txt",
            min_length=config["params"]["blast"]["min_length"],
            min_pct_id=config["params"]["blast"]["min_pct_id"],
        ),
        homology_overlap=expand(
            "results/homology-overlap/homology-{min_length}-bp-{min_pct_id}-pctid-genes-expressed-{{expression}}-overlap-putative-smallrna.unique-genes.txt",
            min_length=config["params"]["blast"]["min_length"],
            min_pct_id=config["params"]["blast"]["min_pct_id"],
        ),
        homology_overlap_downreg=expand(
            "results/homology-overlap/homology-{min_length}-bp-{min_pct_id}-pctid-genes-expressed-{{expression}}-overlap-putative-smallrna-downreg.unique-genes.txt",
            min_length=config["params"]["blast"]["min_length"],
            min_pct_id=config["params"]["blast"]["min_pct_id"],
        ),
    output:
        report(
            "results/summary/genelist-summary-{expression}.txt",
            caption="../report/genelist-summary.rst",
            category="{expression}",
        ),
    log:
        "logs/summary/genelist-summary-{expression}.log",
    conda:
        "../envs/coreutils.yaml"
    shell:
        "wc -l {input:q} > {output:q} 2> {log:q}"
